#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.


xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xsetroot -cursor_name left_ptr
xset -b &
xset r rate 300 50 &
sudo pkill logid
sudo logid &!
sudo pkill logid
keymap.sh
xautolock -time 10 -locker slock &

xinput set-prop 12 "libinput Scroll Method Enabled" 0, 0, 1
xinput set-prop 12 "libinput Button Scrolling Button" 2


autostart="mpd xcompmgr dunst unclutter pipewire transmission-daemon"



spotify

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

