#! /bin/sh


xset -b &
xset r rate 300 50 &
sudo logid &!
sudo nvidia-smi -pm 1
sudo nvidia-smi -pl 155
nvidia-settings -a GPUFanControlState=1 -a GPUTargetFanSpeed=60
export TERM="xterm-256color"

xautolock -time 10 -locker slock &
dunst &!
./.fehbg
#picom --experimental-backends &!
