#!/bin/bash

alias vim="nvim"
alias za="zathura"
alias vi="nvim"
alias ls="exa -l --color=always --group-directories-first"
alias l="exa"
alias c='xclip -selec clip'
alias cp='rsync --progress'
alias in='sudo pacman -S '
alias v='nvim'
alias tsm='transmission-remote'

alias ssh='TERM=xterm-256color ssh'


TMUX_CONFIG="~/.config/tmux/tmux.conf"
alias tn="tmux -u -f $TMUX_CONFIG new" \
      ta="tmux -u -f $TMUX_CONFIG attach" \
      tt="nvim $TMUX_CONFIG"
