#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
echo ~/.config/sxhkd/sxhkdrc | entr -np pkill -USR1 -x sxhkd &

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 &

bspc monitor DisplayPort-2 -d 1 2 3 4 5 6 7 8 9 &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &
sh ../polybar/launch.sh
pgrep bspswallow || bspswallow &
startup

bspc config window_gap 25
bspc config border_width 1

bspc config normal_border_color "#414868"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true                                          

bspc config remove_disabled_monitors true

bspc config remove_unplugged_monitors true


bspc config pointer_follows_monitor true


bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc top_monocle_padding = 15
bspc right_monocle_padding = 15
bspc bottom_monocle_padding = 15
bspc left_monocle_padding = 15
bspc config gapless_monocle false

bspc rule -a Zathura state=tiled
